### ISSUE TITLE
useReducer?

### ISSUE THREAD

**Issue by w3bdesign** [johnkirtley/game-of-thrones#11]
Hi @johnkirtley,

Just saw that you were using multiple useState functions inside of your code.

It may be cleaner and better to replace it with one useReducer function.

I recommend that you take a look at one of my projects on how to implement it:

https://github.com/w3bdesign/todo-hooks

**Comment by johnkirtley** [comment]
I completely agree.
I was planning on going back in and refactoring, but haven't had the time.
